name: Build Project and Check Styling

on:
  push:
    branches: [ "**" ]
    paths:
      - "src/**"
      - "gradle.properties"
      - "build.gradle"
      - "MultiVersion"
      - ".gitmodules"
      - ".github/workflows/build.yml"
    tags-ignore: [ "**" ]

jobs:
  build-and-check:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24.12.0"

      - name: Mark executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Cache IntelliJ IDEA
        uses: actions/cache@v5
        with:
          path: .idea-cache
          key: idea-cache-2025.2.6

      - name: Format with IntelliJ IDEA
        uses: gXLg/intellij-idea-format@80bcbe298215ee142083e278968e8f0064bbc2db
        with:
          idea-url: "https://download.jetbrains.com/idea/ideaIC-2025.2.6.tar.gz"
