name: Lint and Build

on:
  push:
    branches: ["**"]
    paths:
      - "src/**"
      - "gradle.properties"
      - "build.gradle"
      - "MultiVersion"
      - ".gitmodules"
      - ".github/workflows/build.yml"
    tags-ignore: ["**"]

jobs:
  lint-and-build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "18.17.0"

      - name: Google Java Format
        uses: axel-op/googlejavaformat-action@v4.0.0
        with:
          args: "--replace --aosp --skip-sorting-imports --skip-javadoc-formatting"
          skip-commit: true
          files-excluded: "src/main/java/multiversion/*"

      - name: Print diffs
        run: git --no-pager diff --exit-code

      - name: Mark executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build