name: Check Styling and Build

on:
  push:
    branches: [ "**" ]
    paths:
      - "src/**"
      - "gradle.properties"
      - "build.gradle"
      - "MultiVersion"
      - ".gitmodules"
      - ".github/workflows/build.yml"
    tags-ignore: [ "**" ]

jobs:
  check-and-build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24.12.0"

      - name: Cache IntelliJ IDEA
        uses: actions/cache@v5
        with:
          path: /github/workflow/idea-cache
          key: idea-cache-2025-3

      - name: Format with IntelliJ IDEA
        uses: gXLg/intellij-idea-format@2815bf8106f3c62aa2c5e0d525d503de73bf48c7
        with:
          idea-url: "https://download.jetbrains.com/idea/idea-2025.3.tar.gz"

      - name: Mark executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build